### ISSUE TITLE
Question: Is there a recommended formatter?

### ISSUE THREAD

**Issue by vortex-5** [MikeMcl/big.js#119]
Is there a recommended formatter for use with Big.js idealy it would be able to take an arbitrary format string and do different number representation. It doesn't have to be part of big.js if someone has discovered a formatter that works well with strings that's fine with me.

Main issue is most formatters unfortunately are using the number type which can negate the benefits of working in big and getting the higher precision then not being able to display it.

**Comment by MikeMcl** [comment]
There is [toFormat](https://github.com/MikeMcl/toFormat), but it doesn't deal with format strings.

**Comment by blefebvre** [comment]
@vortex-5, `parseFloat` [1] is pretty flexible in terms of the formats it'll make sense of. You may need to process the string beforehand (to remove commas, for example), depending on your input. I'd also recommend looking into `Number.prototype.toLocaleString()` [2] for producing different representations of a given number.

I wrote a bit on this topic, and it includes some sample code (for dealing with different currencies, in particular): https://brucelefebvre.com/blog/2019/01/31/dealing-with-monetary-values-react-native/#handling-different-currencies

In the above example I only call `.toFixed()` when the value is about to be displayed. Otherwise it remains a `Big` value.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat
[2] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

**Comment by vortex-5** [comment]
We already currently use the JS formatting methods the reason for wanting to avoid them is the point of using Big.js is to gain more precision than is available in a double. Using native Number methods requires you cast first to a javascript number losing precision in the process hence why my original question was asking for how to format the number in Big.js while trying to keep it's internal representation and thus preserving the precision.
