### ISSUE TITLE
Round Up

### ISSUE THREAD

**Issue by raybiez** [MikeMcl/big.js#14]
It seems the round up does not work properly. `18.444` rounded up to 2 decimals, is returned as `18.44` instead of `18.45` as expected.

**Comment by 5pitf1re** [comment]
I was only able to find how to round up and down by looking through the source code. Link to this issue comes second as second hit when searching for "bigjs round" in google, so I'm guessing others is looking for how to do it.

Round takes a second optional parameter as number, which tells how it should handle the rounding (up or down). Here's the options:
0 = ROUND_DOWN
1 = ROUND_HALF_UP
2 = ROUND_HALF_EVEN
3 = ROUND_UP 

For example

    new Big(-5.6).round(0, 3)      // -6 ROUND_UP
    new Big(-5.6).round(0, 0)      // -5 ROUND_DOWN

**Comment by MikeMcl** [comment]
@5pitf1re 

Yes, it is in the documentation: [round](http://mikemcl.github.io/big.js/#round) amd [RM](http://mikemcl.github.io/big.js/#rm).
