### ISSUE TITLE
Performance of pow function

### ISSUE THREAD

**Issue by richmondp** [MikeMcl/big.js#187]
Hi Mike, 

I've noticed the performance of the pow() function to be significantly slower in Big.js compared to BigNumber.js. 

A calculation such as `new Big("1.00096153846153846154").pow(2500)` can take up to 6s to calculate vs `new BigNumber("1.00096153846153846154").pow(2500)` which will return in under a second. 

Is this expected behaviour in Big.js?

**Comment by MikeMcl** [comment]
Yes. 

It will be slower because the result of that calculation is over 50,000 digits long and a Big stores a number as an array of single digits e.g. `[1, 2, 3, 4, 5, 6, 7, 8, 9]` while a BigNumber stores the same number as `[123456789]` which makes multiplication much quicker when the number of digits gets high because there are far fewer array elements to operate on.

For normal sized numbers though big.js is often faster and the code is simpler and smaller because of how the values are stored. 

Also, with BigNumbers you can set the `POW_PRECISION` to limit the number of significant digits calculated which canl make the operation faster still.

**Comment by richmondp** [comment]
Thanks for the explanation.
