### ISSUE TITLE
rounding 9.9 gives improper coefficient

### ISSUE THREAD

**Issue by lx-0** [MikeMcl/big.js#191]
When rounding `Big('9.9')`, the resulting Big object will be:
```
Big {
  s: 1,
  e: 1,
  c: [ 1, '-1': NaN ],
  constructor: [Function: Big] {
    DP: 20,
    RM: 1,
    NE: -7,
    PE: 21,
    strict: true,
    roundDown: 0,
    roundHalfUp: 1,
    roundHalfEven: 2,
    roundUp: 3,
    Big: [Circular],
    default: [Circular]
  }
}
```
The index -1 of c is NaN.

**Comment by MikeMcl** [comment]
Thanks for the report. This bug seems to have been present from the beginning. 'Improper' is the right word. 

To reassure other readers, this has no effect on the API or any normal usage of the library.

The bug adds an unwanted property named `'-1'` with value `NaN` to the coefficient array of a Big number returned by `round` when a Big number with a leading nine or nines is rounded up to a Big number which is a power of ten, such as 99.5 rounded up to 100. The unwanted property does not affect the length of the coefficent array or the Big number's value or any operations performed on it.

Thanks again. Fixed in *v6.2.1*.
