### ISSUE TITLE
Precision issue with big.js

### ISSUE THREAD

**Issue by harshrathi-probo** [MikeMcl/big.js#197]
`const result = Big(9.083333333333334).mul(6).toNumber();`
Output => 54.50000000000001
However, if I compute same calculation by normal JS way i.e 
const result = 9.083333333333334 * 6;
Output => 54.5 (which is expected output)

**Comment by harshrathi-probo** [comment]
P.S: I'm using default settings of big.js

**Comment by MikeMcl** [comment]
The mathematically exact result is:

```js
Big('9.083333333333334').mul(6).toString();    // '54.500000000000004'
```

The JavaScript Number constructor parses that result to:

```js
Number("54.500000000000004");    // 54.50000000000001
```

Your expectation is naive. There is no other issue here.

**Comment by MikeMcl** [comment]
The mathematically exact result of `9.083333333333334` multiplied by `6` is `54.500000000000004`.

```js
Big('9.083333333333334').mul(6).toString();    // '54.500000000000004'
```

The JavaScript Number constructor parses that string to `54.50000000000001`.

```js
Number("54.500000000000004");    // 54.50000000000001
```

Why? Because the exact value of the nearest 64-bit floating-point value to
`54.500000000000004`
is
`54.50000000000000710542735760100185871124267578125`
which is closer to 
`54.50000000000001`
then it is to
`54.5`.
```

**Comment by circular17** [comment]
Regarding what happens with JS that gives the expected output result, the number `9.083333333333334` is approximated by JS by something like `0.08333333333333393`.

Multiplied this by 6 with sufficient precision would give `54.5000000000000036` but this is beyond its precision, so JS here outputs the "exact" result 54.5 but that is just lucky.

The input number `9.083333333333334` is of course inaccurate, the actual value would require an infinite quantity of the digit 3. Starting from this value, one could get the target `54.5` by apply a rounding of 15 digits.
