### ISSUE TITLE
Queries for big.js and bignumber.js

### ISSUE THREAD

**Issue by paritosh64ce** [MikeMcl/big.js#199]
Hi Mike,

Thanks for creating multiple libraries to handle values involving higher precision.

I need to make decision to choose one among `bignumber.js` and `big.js`. Could you please help me with below questions? (There is no other way I found apart for raising github issue to get answers)

In [Wiki page](https://github.com/MikeMcl/big.js/wiki) you mentioned...
1. `bignumber.js` and `decimal.js` store values in a higher base than `big.js` so they may be faster when performing operations on values with a large number of digits.
    -  __*Question*__: If I am going to use only 10 as base (no hexadecimal or octa decimal values), is there any advantage of using `bigumber.js` over `big.js`?
   
1. `bignumber.js` is perhaps more suitable for financial applications because the user doesn't need to worry about losing precision unless an operation involving division is used
    - I created two stackblitz to check and found no difference between them when it comes to precision (I have precision unto 18-19 places).
      - Big.js - https://stackblitz.com/edit/angular-material-13-starter-x1xj4z-mgc7wu
      - BigNumber.js - https://stackblitz.com/edit/angular-material-13-starter-x1xj4z-pd6bcm
    - __*Question*__: Is there any advantage of using `bignumber.js` over `big.js` when it comes to precision (again, we are talking about the decimal numbers only - no hexa/octa decimal values)?

**Comment by MikeMcl** [comment]
Hi

1. You seem to misunderstand what I mean here. It is nothing to do with the base *you* are using. I am talking about how values are stored internally. For example, *bignumber.js* stores the digits of the number `1234.56789` as `[ 1234, 56789000000000 ]`, i.e. as an array of two base 1e14 values, whereas *big.js* stores the same number as `[1, 2, 3, 4, 5, 6, 7, 8, 9]`, i.e. as an array of nine base 10 values. Arithmetic operations may be faster with the former because there are fewer elements to process. In practice this would probably only make a difference when using values with hundreds or thousands of digits.

2. I am talking about *bignumber.js* in comparison to *decimal.js*. In the latter, all operations are rounded to the precision setting, so it is possible to lose precision if the setting is too low. In *bignumber.js*, all operations apart from those that use division, always return the exact result.

*bignumber.js* has no advantage over *big.js* regarding precision.

If you don't need the extra features *bignumber.js* offers then use  *big.js *.

**Comment by paritosh64ce** [comment]
Thanks for your answers Mike! 🙇‍♂️
