### ISSUE TITLE
3 letter aliases

### ISSUE THREAD

**Issue by formula1** [MikeMcl/big.js#39]
This is an enhancement, and I can just do it myself, though I figured I'd contact you about it. What would  be nice is to use 3 letter aliases for many of the functions

Example

* `.minus` -> `.sub`
* `.plus` -> `.add`
* `.times` -> `.mul`

Many people, myself included create vector2's in this manner. In addition, the three letters also for kinder code looks

```
a.minus(b)
 .div(c)
 .times(d)
 .plus(e)
```

```
a.sub(b)
 .div(c)
 .mul(d)
 .add(e)
```

The change is simple and I've already done it myself. Just thought I'd throw out the idea to you. https://github.com/formula1/big.js/blob/mutable/big.js#L712

**Comment by MikeMcl** [comment]
Okay, I'll include them. 

You could add a commit when you resend the jshint pull-request.
So the pull request would preferably be
a commit 'Clean-up post-lint'
and a commit 'Add aliases'.

**Comment by formula1** [comment]
I apologize about the delay

**Comment by rdsedmundo** [comment]
@MikeMcl is there any reason why this wasn't done in BigNumber.js as well? I was standardizing between libraries moving from Big.js to BigNumber.js, as we need stuff that is only available in the latter, and was surprised that some of the methods weren't available, only to find this issue here and confirming in the source code that it has only been done to Big.js.

**Comment by rdsedmundo** [comment]
Noticed the same thing for `bigjs.round` vs `bignumberjs.precision`. It's a big odd that the same methods are named differently across the libs.
