### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by tusharmath** [MikeMcl/big.js#44]
Have you compared its performance with other popular libraries?
Such as -
https://nodejsmodules.org/tags/bigint

**Comment by Xotic750** [comment]
Some comparisons would not be fair because the libraries are running on node only and access binaries on the server for their implementations.

e.g.
https://www.npmjs.com/package/bigint uses libgmp
https://www.npmjs.com/package/bignum use OpenSSL

No good comparing apples to oranges.

You will notice though, that there are comparisons with some popular packages that are Javascript implementations. Read the README and look in the perf directory of the repository.

**Comment by MikeMcl** [comment]
This isn't a big integer library, and its arithmetic methods will be considerably slower than some big integer libraries when handling integers with a large number of digits (as in cryptography for example). 

Why slower? Well, it handles non-integers and numbers in scientific notation, and checks all inputs, and it stores numbers in a simple and accessible base 10 format rather than using a much higher base which would make operations on numbers with many digits much faster, etc...

For normal-sized inputs in common use-cases the difference in speed between this and any faster big integer libraries is likely to be pretty insignificant.

**Comment by slidenerd** [comment]
I know this is a really old question but I couldnt find any benchmarks where I could see how bigjs does against normal floating pointing addition. I know it will be slower, I am just interested to see the magnitudes to get a clear picture. Couldnt find anything on jsperf so far that does bigjs to float, would appreciate if you made such a comparison somewhere

**Comment by johnmanko** [comment]
A very basic test:

```javascript
const A_FLOAT = 1.234;
const B_BIGJS = new Big("1.234");
const LOOP_COUNT = 10000000;

var a = 0;
// float
var startTime = Date.now();
for(var i = 0; i <= LOOP_COUNT; i++) {
   a = a + A_FLOAT;
}
var stopTime = Date.now();
console.log("float addition (adding " + A_FLOAT + " " + LOOP_COUNT + " times) yielding " + a + " : " + (stopTime - startTime) + " milliseconds");

a = A_FLOAT;
startTime = Date.now();
for(var i = 0; i <= LOOP_COUNT; i++) {
   a = a * 2;
}
stopTime = Date.now();
console.log("float multiplication (double " + A_FLOAT + " " + LOOP_COUNT + " times) yielding " + a + ": " + (stopTime - startTime) + " milliseconds");

// Big

var b = new Big("0.0");
startTime = Date.now();
for(var i = 0; i <= LOOP_COUNT; i++) {
   b = b.plus(B_BIGJS);
}
stopTime = Date.now();
console.log("Big addition (adding " + B_BIGJS + " " + LOOP_COUNT + " times) yielding " + b.toFixed(3) + " : " + (stopTime - startTime) + " milliseconds");

b = new Big("0.0");
var two = new Big("2.0");
startTime = Date.now();
for(var i = 0; i <= LOOP_COUNT; i++) {
   b = b.times(two);
}
stopTime = Date.now();
console.log("Big multiplication (double " + B_BIGJS + " " + LOOP_COUNT + " times) yielding " + b.toFixed(3) + ": " + (stopTime - startTime) + " milliseconds");
```


//First run
```
float addition (adding 1.234 10000000 times) yielding 12340001.232410042 : 18 milliseconds _display:89:1
float multiplication (double 1.234 10000000 times) yielding Infinity: 19 milliseconds _display:97:1
Big addition (adding 1.234 10000000 times) yielding 12340001.234 : 6367 milliseconds _display:107:1
Big multiplication (double 1.234 10000000 times) yielding 0.000: 3737 milliseconds _display:116:1
```

//Second run
```
float addition (adding 1.234 10000000 times) yielding 12340001.232410042 : 15 milliseconds _display:89:1
float multiplication (double 1.234 10000000 times) yielding Infinity: 18 milliseconds _display:97:1
Big addition (adding 1.234 10000000 times) yielding 12340001.234 : 6450 milliseconds _display:107:1
Big multiplication (double 1.234 10000000 times) yielding 0.000: 3891 milliseconds
```

**Comment by slidenerd** [comment]
Super thanks for adding those!!!
