### ISSUE TITLE
big.js vs. bignumber.js vs. decimal.js?

### ISSUE THREAD

**Issue by rauschma** [MikeMcl/big.js#45]
Suggestion: describe in the readme how these three libraries differ. AFAICT, big.js only supports base 10, whereas bignumber.js supports arbitrary bases. But what distinguishes decimal.js from big.js?

**Comment by rauschma** [comment]
Ah! I found a good explanation in the repository for decimal.js. Still, a cheat sheet explaining which of the three libraries are best used in which situation may make sense.

**Comment by MikeMcl** [comment]
There's also #2 , but yes I take your point. I need to set the differences down in one place that I can then link to from each repository. I'll address the matter soon. Thanks for the feedback.

**Comment by rauschma** [comment]
You’re welcome. It’s been a joy working with decimal.js (good docs, simply install via npm, etc.).

**Comment by PilotBob** [comment]
@rauschma Where did you find the comparison document. I can't see it. I had the same question.

**Comment by MikeMcl** [comment]
@PilotBob 

In short:

**big.js**: minimalist; easy-to-use; precision specified in decimal places; precision applied to division only.  
**bignumber.js**: bases 2-64; configuration options; `NaN`; `Infinity`; precision specified in decimal places; precision applied to division only; base prefixes.  
**decimal.js**:  bases 2-64; configuration options; `NaN`; `Infinity`; non-integer powers, `exp`, `ln`, `log`; precision specified in significant digits; precision always applied; random numbers.

At length:

*big.js* is a minimalist arbitrary-precision library. It is the simplest and smallest of the three, less than half the size of *bignumber.js* and with only half the number of methods. It doesn't accept `NaN` or `Infinity` as legitimate values, it doesn't work with numbers of other bases, and the only runtime configuration available is the ability to set the number of decimal places and rounding mode of operations involving division.

    Big.DP = 7;
    Big.RM = 4;             // round half-up
    var x = new Big(5);
    x.div(3).toString();    // '1.6666667' 

Like the other two libraries, it includes `toExponential`, `toFixed` and `toPrecision` methods. Unlike the others, it stores values in base 10 which makes it easy to change the properties of a Big directly if required

    var x = new Big('123.456');
    x.c;             // [1, 2, 3, 4, 5, 6] (coefficient, i.e. significand/mantissa)
    x.e;             // 2 (exponent)
    x.s;             // 1 (sign)
    x.e = -3;
    x.toString();    // '0.00123456'

*bignumber.js* and *decimal.js* store values in a higher base than *big.js* so they will be faster when performing operations on values with a large number of digits. They also support `NaN` and `Infinity` and can work with values in other bases (2 to 64 inclusive).
 
    var x = new BigNumber('ff.8', 16);
    x.toString();      // '255.5'
    x.toString(16);    // 'ff.8'

*bignumber.js* and *decimal.js* also have various runtime configuration options, such as the ability to set the exponent value at which `toString` produces exponential notation.

    var x = new Decimal(987654321);
    x.toString();    // '987654321'
    Decimal.config({ toExpPos: 4 });
    x.toString();    // '9.87654321e+8'

*decimal.js* was orginally intended to be version two of *bignumber.js* but I decided to make them separate libraries. The main difference between them is that with *decimal.js* precision is specified in terms of significant digits instead of decimal places, and all calculations are rounded to the precision (similar to Python's decimal module) rather than just those involving division. 

    Bignumber.config({ DECIMAL_PLACES: 3, ROUNDING_MODE; 1 });
    var x = new BigNumber('123.456789');
    x.plus(1).toString();    // '124.456789'
  
    Decimal.config({ precision: 7, rounding: 4 });
    var y = new Decimal('123.456789');
    y.plus(1).toString();    // '124.4568'

This could be considered to make *bignumber.js* easier to use than *decimal.js*, and perhaps more suitable for financial applications, because the user doesn't need to worry about losing precision unless an operation involving division is used.
 
Conversely, *decimal.js* may be considered better for more scientifc applications as it can handle very small or large values more efficiently: for example, it does not have the limitation of binumber.js that if adding a BigNumber value with a small exponent to one with a large exponent, *bignumber.js* will attempt to perform the operation to full precision which may involve the creation of a massive array, and consequently cause the operation to hang.

*decimal.js* also adds `exp`, `ln`, `log` and `random` functions, among others, and supports non-integer powers, which *bignumber.js* does not. These additions make *decimal.js* significantly larger than *bignumber.js*.

One thing that *bignumber.js* has that *decimal.js* currently does not, is support for binary, octal and hexadecimal prefixes

    var x = new BigNumber('0b1101');
    x.toString()    // '13'

**Comment by PilotBob** [comment]
Excellent information. Thanks.

**Comment by MikeMcl** [comment]
@PilotBob 
@PilotBob 

Yes, and yes.
Perhaps I should have written "rounding" not "precision". I'm going to change it above.

**Comment by MikeMcl** [comment]
Added the above description of the differences between the libraries to the Wiki, and a link to it from the README.

**Comment by adamreisnz** [comment]
> In short:
> big.js: minimalist; easy-to-use; precision specified in decimal places; precision applied to division only.
> bignumber.js: bases 2-64; configuration options; NaN; Infinity; precision specified in decimal places; precision applied to division only; base prefixes.
> decimal.js: bases 2-64; configuration options; NaN; Infinity; non-integer powers, exp, ln, log; precision specified in significant digits; precision always applied; random numbers.

So if I understand this correctly, neither of the libraries allows for precision to be specified in decimal places _and_ always be applied?

That's the one combination I need for financial calculations.

**Comment by MikeMcl** [comment]
@adamreisnz 

To round to decimal places:

*big.js*
```js
x = new Big(123.456)
x = x.plus(0.78).round(2)
```

*bignumber.js*
```js
x = new BigNumber(123.456)
x = x.plus(0.78).decimalPlaces(2)
```

Please don't make further comments in this thread.

**Comment by ackvf** [comment]
The description https://github.com/MikeMcl/big.js/issues/45#issuecomment-104211175 is not in the docs any more? http://mikemcl.github.io/big.js

**Comment by MikeMcl** [comment]
@ackvf 

The link is there in the README on the second line under the title.
